# Generated by Django 2.2.1 on 2019-11-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrVisitorInfo',
            fields=[
                ('id', models.CharField(db_column='id', max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('app_name', models.CharField(blank=True, max_length=40, verbose_name='子系统模块名')),
                ('visitor_type', models.CharField(blank=True, choices=[('read', '阅读')], max_length=10, verbose_name='访客类型')),
                ('link_id', models.CharField(blank=True, max_length=40, verbose_name='关联id')),
                ('visitor_ip', models.CharField(blank=True, max_length=20, verbose_name='访问者ip')),
                ('visitor_lat', models.CharField(blank=True, max_length=30, verbose_name='访问者纬度')),
                ('visitor_lng', models.CharField(blank=True, max_length=30, verbose_name='访问者经度')),
                ('visitor_city', models.CharField(blank=True, max_length=30, verbose_name='访问者城市')),
                ('visitor_addr', models.TextField(blank=True, null=True, verbose_name='访问者位置描述')),
                ('cnt_ipstack', models.IntegerField(default=0, verbose_name='解析次数_ipstack')),
            ],
            options={
                'db_table': 'dr_visitor_info',
            },
        ),
    ]
