# Generated by Django 2.2.1 on 2019-11-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.CharField(db_column='id', max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, db_column='title', db_index=True, max_length=50, verbose_name='标题')),
                ('title_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='摘要描述')),
                ('blog_type', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='类别')),
                ('blog_tags', models.TextField(blank=True, db_index=True, verbose_name='标签')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('read_level', models.IntegerField(default=0, verbose_name='阅读级别')),
                ('read_cnt', models.IntegerField(default=0, verbose_name='阅读量')),
                ('bg_url', models.TextField(blank=True, null=True, verbose_name='背景图')),
                ('auth_account', models.CharField(blank=True, max_length=50, verbose_name='作者用户名')),
                ('auth_name', models.CharField(blank=True, max_length=50, verbose_name='作者姓名')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'blog_content',
            },
        ),
        migrations.CreateModel(
            name='BlogParam',
            fields=[
                ('param_code', models.CharField(db_column='param_code', max_length=30, primary_key=True, serialize=False, verbose_name='code')),
                ('param_name', models.TextField(blank=True, verbose_name='名称')),
                ('param_value', models.TextField(blank=True, null=True, verbose_name='参数值')),
                ('param_notes', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'blog_param',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('type_id', models.CharField(db_column='type_id', max_length=2, primary_key=True, serialize=False, verbose_name='type_id')),
                ('type_name', models.CharField(blank=True, choices=[('fx', '分享'), ('zz', '转载'), ('bj', '笔记'), ('gw', '感悟')], db_index=True, max_length=10, verbose_name='类别')),
            ],
            options={
                'db_table': 'blog_type',
            },
        ),
    ]
